apiVersion: v1
kind: Service
metadata:
  name: triage-api
  labels:
    app: triage-api
spec:
  type: LoadBalancer
  selector:
    app: triage-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
