apiVersion: v1
kind: Service
metadata:
  name: hospital-triage-api-service
  labels:
    app: hospital-triage-api
spec:
  type: LoadBalancer
  selector:
    app: hospital-triage-api
  ports:
    - name: http
      protocol: TCP
      port: 80        # Puerto público del LoadBalancer
      targetPort: 80  # Puerto donde escucha FastAPI dentro del contenedor
