apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-triage-api
  labels:
    app: hospital-triage-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-triage-api
  template:
    metadata:
      labels:
        app: hospital-triage-api
    spec:
      containers:
        - name: hospital-triage-api
          image: silvita/hospital-triage-api:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
