apiVersion: v1
kind: Service
metadata:
  name: triage-api
spec:
  type: LoadBalancer
  selector:
    app: triage-api
  ports:
    - name: http
      port: 80          # puerto público del LB
      targetPort: 8000  # puerto donde escucha FastAPI dentro del pod
      nodePort: 31242   # NodePort FIJO (ya permitido en el firewall)
